### ISSUE TITLE
get_events view

### ISSUE THREAD

**Issue by Alkandari-Y** [devq8/event_planner#4]
As mentioned before, the code in the get_events view function in the planner is lengthy and could be in its own separate function. This could be made more concise using django queries to avoid having to perform all the logic in the view function using filters conditionally based on the user object

Check out this link from django [queries](https://docs.djangoproject.com/en/4.0/topics/db/queries/#filtered-querysets-are-unique) docs

**Comment by devq8** [comment]
We rewrite the code.
It's now much better.
